server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kon_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 183808
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      #限制文件上传大小
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    #标准输出流  日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss

knife4j:
  enable: true
  openapi:
    title: 文章列表接口文档
    description: "文章列表接口文档"
    email: Jay@kon.cn
    concat: 虎哥
    url: https://www.kon.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.kon.controller